// Owned synthetic fixtures only. Never point this script at the NAS.
import assert from 'node:assert/strict'
import { randomUUID, randomBytes } from 'node:crypto'
import { mkdir, writeFile } from 'node:fs/promises'
import { unzipSync, strFromU8 } from 'fflate'
import { PrismaClient } from '@prisma/client'
import bcrypt from 'bcryptjs'
import { chat } from '../src/lib/ai'
import { runAssessmentJob } from '../src/lib/assessment-worker.server'
import { collectEvidence } from '../src/lib/assessment-data.server'
import type { AssessmentQuestion } from '../src/lib/assessments'
const base = process.env.GA_BASE_URL
const url = new URL(process.env.DATABASE_URL || 'file:///missing')
assert.equal(base, 'http://127.0.0.1:3459'); assert.equal(url.hostname, '127.0.0.1'); assert.equal(url.port, '55439'); assert.equal(url.pathname, '/sanctum_ga_check')
async function main() {
  const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright')
  const browser = await chromium.launch({ headless: true })
  const db = new PrismaClient({ log: [] })
  const suffix = randomUUID(), password = randomBytes(24).toString('base64url'), passwordHash = await bcrypt.hash(password, 10)
  const users: any[] = [], classes: any[] = []; const errors: string[] = []
  const output = process.env.ASSESSMENT_QA_OUTPUT || '/tmp/sanctum-course-check'
  await mkdir(output, { recursive: true })
  let passCount = 0
  const pass = (s: string) => { passCount++; console.log('PASS ' + s) }
  async function login(u: any) {
    const context = await browser.newContext({ baseURL: base, viewport: { width: 1440, height: 1000 } })
    const csrf = await (await context.request.get('/api/auth/csrf')).json()
    await context.request.post(u.role === 'OBSERVER' ? '/api/auth/callback/observer' : '/api/auth/callback/credentials', { form: { csrfToken: csrf.csrfToken, email: u.email, password, callbackUrl: base, json: 'true' } })
    const loggedIn = (await (await context.request.get('/api/auth/session')).json()).user
    assert.ok(loggedIn, `Login failed for ${u.role}`)
    assert.equal(loggedIn.role, u.role)
    const page = await context.newPage(); page.on('pageerror', (e: Error) => errors.push(e.message))
    return { context, page, api: context.request }
  }
  try {
    for (const [firstName, role] of [['Staff', 'ADMIN'], ['Student', 'TEAM_LEAD'], ['Other', 'MEMBER'], ['Observer', 'OBSERVER']]) users.push(await db.user.create({ data: { firstName, lastName: 'CourseQA', email: `${firstName}-${suffix}@example.invalid`, passwordHash, role: role as any } }))
    for (let i = 0; i < 2; i++) classes.push(await db.classWorkspace.create({ data: { name: `Course QA ${suffix}-${i}`, createdById: users[0].id, members: { create: (i ? [users[2]] : users.slice(0, 3)).map(u => ({ userId: u.id })) } } }))
    const team = await db.team.create({ data: { name: 'Team One QA', classWorkspaceId: classes[0].id, members: { create: { userId: users[1].id, role: 'LEAD' } } } })
    const otherTeam = await db.team.create({ data: { name: 'Team Two QA', classWorkspaceId: classes[0].id } })
    const evidence = [
      ['Configure Linux SSH authentication', 'Configured an SSH daemon with public-key authentication. Created an Ed25519 key pair, installed the public key in authorized_keys, checked file ownership and permissions, disabled password login after testing a second session, and reviewed auth logs for failed access attempts. Verified service status and firewall rules.'],
      ['Troubleshoot DNS resolution', 'Compared recursive lookup results with dig and nslookup. Checked authoritative records, A and AAAA responses, TTL and caching. Distinguished NXDOMAIN from SERVFAIL. Flushed a local cache, compared results against an internal DNS server, and checked TCP and UDP port 53 connectivity. Recorded test results and the root cause.'],
      ['Analyze network traffic', 'Captured synthetic lab traffic with tcpdump and inspected the packets in Wireshark. Applied capture and display filters. Identified the TCP three-way handshake, retransmissions, and DNS queries. Compared source and destination addresses, ports and sequence numbers to diagnose an intentionally blocked connection in the lab.'],
    ]
    const tickets: { id: string }[] = []
    for (const [title, description] of evidence) tickets.push(await db.ticket.create({ data: { title, description, status: 'DONE', teamId: team.id, createdById: users[1].id, assigneeId: users[1].id, startDate: new Date('2026-09-01'), dueDate: new Date('2026-10-10'), startedAt: new Date('2026-09-02'), completedAt: new Date('2026-09-20') } }))
    await db.ticket.create({ data: { title: 'Secret other team sentinel', description: 'Must not export with Team One.', teamId: otherTeam.id, createdById: users[0].id } })
    const delegated = await db.ticket.create({ data: { title: 'Delegated task sentinel', description: evidence[0][1], status: 'DONE', teamId: team.id, createdById: users[1].id, assigneeId: users[2].id } })
    const collected = await collectEvidence(db, users[1].id, classes[0].id, '2026-01-01', '2026-12-31')
    assert.ok(!collected.some(e => e.id === delegated.id)); assert.equal(collected.length, 3)
    pass('evidence uses assigned work and does not count creating someone else’s ticket')
    const admin = await login(users[0]), student = await login(users[1]), other = await login(users[2]), observer = await login(users[3])
    await student.page.goto('/?classId=' + classes[0].id)
    const panel = student.page.getByRole('button', { name: /Team One QA.*member/ })
    await panel.waitFor(); assert.equal(await panel.getAttribute('aria-expanded'), 'false')
    await student.page.waitForFunction(() => Array.from(document.querySelectorAll('button')).some(el => Object.keys(el).some(key => key.startsWith('__reactProps'))))
    await panel.click(); await student.page.locator('button[aria-expanded="true"]').filter({ hasText: 'Team One QA' }).waitFor()
    assert.equal(await student.page.getByRole('button', { name: /Team Two QA.*member/ }).getAttribute('aria-expanded'), 'false')
    await panel.click(); await student.page.keyboard.press('n')
    assert.equal(await student.page.getByRole('dialog').count(), 0)
    await student.page.screenshot({ path: output + '/collapsed-teams.png', fullPage: true })
    pass('teams start collapsed, expand independently, and hidden boards ignore keyboard shortcuts')
    await student.page.getByRole('button', { name: 'Export Team One QA', exact: true }).click()
    await student.page.getByLabel('View', { exact: true }).selectOption('gantt')
    await student.page.getByLabel('From', { exact: true }).fill('2026-09-01')
    await student.page.getByLabel('Through', { exact: true }).fill('2026-10-31')
    for (const paper of ['letter', 'tabloid']) {
      await student.page.getByLabel('Paper size').selectOption(paper)
      const link = await student.page.getByRole('link', { name: 'Print / Save PDF' }).getAttribute('href')
      const exportPage = await student.context.newPage()
      const response = await exportPage.goto(link)
      assert.equal(response.status(), 200)
      const html = await exportPage.content(); assert.ok(!html.includes('Secret other team sentinel'))
      await exportPage.pdf({ path: `${output}/team-gantt-${paper}.pdf`, preferCSSPageSize: true, printBackground: true })
      await exportPage.screenshot({ path: `${output}/team-gantt-${paper}.png`, fullPage: true })
      await exportPage.close()
    }
    const query = '?view=gantt&paper=letter&from=2026-09-01&to=2026-10-31'
    assert.equal((await student.api.get(`/api/teams/${team.id}/export${query}`)).status(), 200)
    const outside = await db.team.create({ data: { name: 'Outside course', classWorkspaceId: classes[1].id } })
    assert.equal((await student.api.get(`/api/teams/${outside.id}/export${query}`)).status(), 404)
    pass('team-only exports preserve class permissions and render Letter/Tabloid PDFs')
    const payload = { classId: classes[0].id, studentId: users[1].id, from: '2026-01-01', to: '2026-12-31', mode: 'PRACTICE' }
    assert.equal((await other.api.post('/api/assessments', { data: payload })).status(), 404)
    assert.equal((await observer.api.post('/api/assessments', { data: payload })).status(), 404)
    assert.equal((await student.api.post('/api/assessments', { data: { ...payload, mode: 'EXAM' } })).status(), 403)
    const queuedResponse = await student.api.post('/api/assessments', { data: payload }); assert.equal(queuedResponse.status(), 202)
    const queued = await queuedResponse.json()
    assert.equal((await student.api.post('/api/assessments', { data: payload })).status(), 409)
    let batch = 0
    const fake = async (messages: any[]) => {
      const data = JSON.parse(messages[1].content), kind = data.kind
      const questions = Array.from({ length: data.questionCount }, (_, i) => ({ stem: `For version ${data.version}, scenario ${batch * 5 + i}, which diagnostic action provides evidence?`, options: ['Inspect service logs', 'Discard all logs', 'Ignore failures', 'Delete every configuration'], correctIndex: 0, explanation: 'Inspecting service logs supplies observed evidence. Discarding logs removes evidence; ignoring failures does not diagnose them; deleting configuration is destructive.', kind, sourceIds: [tickets[i % tickets.length].id] }))
      batch++; return JSON.stringify({ questions })
    }
    await runAssessmentJob(db, fake)
    const ready = await (await student.api.get(`/api/assessments/${queued.id}`)).json()
    assert.equal(ready.status, 'READY'); assert.equal(ready.questions.length, 25)
    assert.ok(!JSON.stringify(ready).includes('correctIndex')); assert.ok(!JSON.stringify(ready).includes('explanation'))
    assert.equal((await other.api.get(`/api/assessments/${queued.id}`)).status(), 404)
    pass('persistent generation validates 25 questions, isolates students, and withholds answer keys')
    await student.page.goto('/assessments')
    await student.page.getByLabel('Course', { exact: true }).selectOption(classes[0].id)
    await student.page.getByRole('button', { name: /Practice · READY/ }).click()
    await student.page.getByRole('group', { name: 'Question 1 · concept', exact: true }).waitFor()
    for (let i = 0; i < 25; i++) await student.page.locator(`input[name="question-${i}"]`).first().check()
    await student.page.getByRole('button', { name: 'Submit all 25 answers' }).click()
    await student.page.getByText(/Practice score:/).waitFor()
    await student.page.screenshot({ path: output + '/practice-result.png', fullPage: true })
    const submitted = await (await student.api.get(`/api/assessments/${queued.id}`)).json()
    assert.ok(submitted.questions[0].explanation)
    assert.equal((await student.api.patch(`/api/assessments/${queued.id}`, { data: { action: 'submit', answers: Array(25).fill(0) } })).status(), 409)
    pass('students complete a practice test in-browser and cannot resubmit the saved attempt')
    await db.assessment.update({ where: { id: queued.id }, data: { createdAt: new Date(Date.now() - 120000) } })
    const exam = await (await admin.api.post('/api/assessments', { data: { ...payload, mode: 'EXAM', references: 'Use evidence-based troubleshooting.' } })).json()
    assert.ok(exam.id); batch = 0; await runAssessmentJob(db, fake)
    assert.equal((await student.api.get(`/api/assessments/${exam.id}`)).status(), 404)
    assert.equal((await student.api.get(`/api/assessments/${exam.id}/export?key=1`)).status(), 403)
    assert.equal((await admin.api.get(`/api/assessments/${exam.id}/export`)).status(), 409)
    await admin.page.goto('/assessments'); await admin.page.getByLabel('Course', { exact: true }).selectOption(classes[0].id); await admin.page.getByLabel('Student', { exact: true }).selectOption(users[1].id)
    await admin.page.getByRole('button', { name: /Exam · READY/ }).click()
    const selectedTest = admin.page.getByRole('region', { name: 'Selected test' })
    await admin.page.getByLabel('Question 1 text', { exact: true }).waitFor()
    assert.ok(await selectedTest.evaluate((el: HTMLElement) => document.activeElement === el))
    assert.ok((await selectedTest.boundingBox()).y >= 0)
    assert.ok((await admin.page.getByRole('button', { name: 'Accept exam', exact: true }).boundingBox()).y < 1000)
    await admin.page.getByLabel('Question 1 text', { exact: true }).fill('Which observation gives the strongest evidence of a successful SSH authentication?')
    await admin.page.getByRole('button', { name: /Open assessment.*Exam · READY/ }).click()
    assert.equal(await admin.page.getByLabel('Question 1 text', { exact: true }).inputValue(), 'Which observation gives the strongest evidence of a successful SSH authentication?')
    await admin.page.getByRole('button', { name: 'Save edits', exact: true }).click()
    await admin.page.getByRole('button', { name: 'Accept exam', exact: true }).click()
    await admin.page.getByRole('link', { name: 'Print student exam', exact: true }).waitFor()
    const accepted = await (await admin.api.get(`/api/assessments/${exam.id}`)).json(); assert.equal(accepted.approvalMethod, 'EDITED')
    const testHtml = await (await admin.api.get(`/api/assessments/${exam.id}/export`)).text()
    const keyHtml = await (await admin.api.get(`/api/assessments/${exam.id}/export?key=1`)).text()
    assert.ok(!testHtml.includes('Inspecting service logs supplies')); assert.ok(keyHtml.includes('Inspecting service logs supplies'))
    pass('instructor edits and accepts a private exam with separate student and answer-key exports')
    const exportBody = { classId: classes[0].id, ids: [exam.id], format: 'qti', points: 4 }
    assert.equal((await student.api.post('/api/assessments/canvas', { data: exportBody })).status(), 403)
    assert.equal((await observer.api.post('/api/assessments/canvas', { data: exportBody })).status(), 403)
    assert.equal((await admin.api.post('/api/assessments/canvas', { data: { ...exportBody, classId: classes[1].id } })).status(), 404)
    assert.equal((await admin.api.post('/api/assessments/canvas', { data: { ...exportBody, points: 0 } })).status(), 400)
    assert.equal((await admin.api.post('/api/assessments/canvas', { data: { ...exportBody, ids: [exam.id, queued.id], format: 'individual' } })).status(), 200)
    const classic = await admin.api.post('/api/assessments/canvas', { data: { classId: classes[0].id, latestApproved: true, format: 'qti', points: 4 } })
    assert.equal(classic.status(), 200); assert.equal(classic.headers()['cache-control'], 'private, no-store')
    const classicBytes = await classic.body(); await writeFile(output + '/synthetic-classic.zip', classicBytes)
    const qti = unzipSync(classicBytes), content = strFromU8(Object.entries(qti).find(([p]) => p.endsWith('/assessment.xml'))![1])
    assert.equal((content.match(/<item ident=/g) || []).length, 25)
    const exportedAnswers = Array.from(content.matchAll(/<varequal respident="response1">choice_(\d)<\/varequal>/g), m => Number(m[1]))
    assert.deepEqual(exportedAnswers, accepted.questions.map((q: AssessmentQuestion) => q.correctIndex))
    assert.ok(!content.includes('Use evidence-based troubleshooting.'))
    const individual = await admin.api.post('/api/assessments/canvas', { data: { ...exportBody, ids: [exam.id, queued.id], format: 'individual' } })
    await writeFile(output + '/synthetic-new-quizzes.zip', await individual.body())
    assert.equal(Object.keys(unzipSync(await individual.body())).filter(p => p.endsWith('.zip')).length, 2)
    const downloaded = admin.page.waitForEvent('download')
    await admin.page.getByRole('button', { name: 'Export Canvas quiz (100 points)', exact: true }).click()
    assert.match((await downloaded).suggestedFilename(), /canvas-qti/)
    await selectedTest.getByLabel('Canvas quiz type').selectOption('new')
    await selectedTest.getByText(/create a New Quiz/).waitFor()
    await selectedTest.getByLabel('Quiz points per question').fill('2')
    const customDownload = admin.page.waitForEvent('download')
    const customRequest = admin.page.waitForRequest((request: any) => request.url().endsWith('/api/assessments/canvas') && request.method() === 'POST')
    await selectedTest.getByRole('button', { name: 'Export Canvas quiz (50 points)', exact: true }).click()
    await customDownload
    assert.equal((await customRequest).postDataJSON().points, 2)
    await selectedTest.getByLabel('Quiz points per question').fill('4')
    pass('Canvas exports preserve all answer mappings, offer quiz type and custom points, deny students and exclude references')
    await db.assessment.createMany({ data: Array.from({ length: 51 }, (_, i) => ({ studentId: users[1].id, classWorkspaceId: classes[0].id, createdById: users[0].id, mode: 'EXAM', status: 'FAILED', from: '2026-01-01', to: '2026-12-31', sources: [], promptVersion: 'synthetic-library', createdAt: new Date(Date.now() - (i + 10) * 60000) })) })
    const listed = await (await admin.api.get(`/api/assessments/library?classId=${classes[0].id}`)).json()
    assert.equal(listed.total, 53); assert.equal(listed.items.length, 25)
    const lastPage = await (await admin.api.get(`/api/assessments/library?classId=${classes[0].id}&page=3`)).json()
    assert.equal(lastPage.items.length, 3)
    assert.ok(!JSON.stringify(listed).includes('correctIndex')); assert.ok(!JSON.stringify(listed).includes('sources'))
    assert.equal((await student.api.get('/api/assessments/library?classId=all')).status(), 404)
    assert.equal((await other.api.get(`/api/assessments/library?classId=${classes[0].id}&studentId=${users[1].id}`)).status(), 404)
    const personal = await (await student.api.get(`/api/assessments/library?classId=${classes[0].id}`)).json()
    assert.equal(personal.total, 1)
    await admin.page.goto('/assessments')
    await admin.page.getByLabel('Course', { exact: true }).selectOption(classes[0].id)
    const library = admin.page.getByRole('region', { name: 'Assessment library' })
    await library.getByText('53 saved versions · Page 1 of 3', { exact: true }).waitFor()
    await library.getByRole('button', { name: 'Next page' }).click()
    await library.getByText('53 saved versions · Page 2 of 3', { exact: true }).waitFor()
    await library.getByRole('button', { name: 'Next page' }).click()
    await library.getByText('53 saved versions · Page 3 of 3', { exact: true }).waitFor()
    await library.getByLabel('Assessment status').selectOption('APPROVED')
    await library.getByText('1 saved version · Page 1 of 1', { exact: true }).waitFor()
    const detailRoute = `**/api/assessments/${exam.id}`
    await admin.page.route(detailRoute, (route: any) => route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: 'Synthetic temporary load failure.' }) }))
    await library.getByRole('button', { name: /Open assessment/ }).click()
    await selectedTest.getByText('Could not load this assessment: Synthetic temporary load failure.', { exact: true }).waitFor()
    assert.equal(await selectedTest.getByRole('button', { name: 'Export Canvas quiz (100 points)' }).count(), 0)
    await admin.page.unroute(detailRoute)
    await selectedTest.getByRole('button', { name: 'Retry opening assessment' }).click()
    await selectedTest.getByRole('button', { name: 'Export Canvas quiz (100 points)' }).waitFor()
    assert.ok(await selectedTest.evaluate((el: HTMLElement) => document.activeElement === el))
    assert.ok((await selectedTest.getByRole('button', { name: 'Export Canvas quiz (100 points)' }).boundingBox()).y < 1000)
    await admin.page.setViewportSize({ width: 390, height: 844 })
    await library.getByRole('button', { name: /Open assessment/ }).click()
    assert.ok((await selectedTest.boundingBox()).y >= 0)
    const exportBox = await selectedTest.getByRole('button', { name: 'Export Canvas quiz (100 points)' }).boundingBox()
    assert.ok(exportBox.x >= 0 && exportBox.x + exportBox.width <= 390)
    await admin.page.screenshot({ path: output + '/assessment-open-mobile.png' })
    await admin.page.setViewportSize({ width: 1440, height: 1000 })
    pass('opening assessments focuses the questions/actions, preserves edits and retries failed loads on desktop and mobile')
    await library.getByLabel('Select exportable assessments on this page').check()
    const classDownload = admin.page.waitForEvent('download')
    await library.getByRole('button', { name: 'Export selected (1)' }).click()
    await classDownload
    await admin.page.screenshot({ path: output + '/assessment-library-desktop.png', fullPage: true })
    await admin.page.setViewportSize({ width: 390, height: 844 })
    await admin.page.screenshot({ path: output + '/assessment-library-mobile.png', fullPage: true })
    await admin.page.setViewportSize({ width: 1440, height: 1000 })
    pass('assessment library exposes history beyond 50, class/student filters and browser batch downloads')
    const failedIds = (await db.assessment.findMany({ where: { classWorkspaceId: classes[0].id, status: 'FAILED' }, select: { id: true } })).map(a => a.id)
    const failedData = { studentId: users[2].id, classWorkspaceId: classes[1].id, createdById: users[0].id, mode: 'EXAM' as const, status: 'FAILED' as const, from: '2026-01-01', to: '2026-12-31', sources: [], promptVersion: 'synthetic-cleanup' }
    const foreignFailure = await db.assessment.create({ data: failedData })
    const pendingFixture = await db.assessment.create({ data: { ...failedData, classWorkspaceId: classes[0].id, status: 'QUEUED' } })
    const cleanBody = { classId: classes[0].id, allFailed: true }
    const anonymous = await browser.newContext({ baseURL: base })
    assert.equal((await anonymous.request.delete('/api/assessments/failed', { data: cleanBody })).status(), 401)
    await anonymous.close()
    for (const client of [student, other, observer]) assert.equal((await client.api.delete('/api/assessments/failed', { data: cleanBody })).status(), 403)
    assert.equal((await admin.api.delete('/api/assessments/failed', { data: { classId: 'all', allFailed: true } })).status(), 400)
    assert.equal((await admin.api.delete('/api/assessments/failed', { data: { classId: classes[0].id } })).status(), 400)
    for (const id of [exam.id, queued.id, pendingFixture.id, foreignFailure.id]) assert.equal((await admin.api.delete('/api/assessments/failed', { data: { classId: classes[0].id, id } })).status(), 409)
    await library.getByLabel('Assessment status').selectOption('FAILED')
    await library.getByText('51 saved versions · Page 1 of 3', { exact: true }).waitFor()
    await library.getByRole('button', { name: /Open assessment/ }).first().click()
    await selectedTest.getByRole('button', { name: 'Delete failed attempt', exact: true }).waitFor()
    admin.page.once('dialog', (dialog: any) => dialog.dismiss())
    await selectedTest.getByRole('button', { name: 'Delete failed attempt', exact: true }).click()
    assert.equal(await db.assessment.count({ where: { id: { in: failedIds } } }), 51)
    admin.page.once('dialog', (dialog: any) => dialog.accept())
    await selectedTest.getByRole('button', { name: 'Delete failed attempt', exact: true }).click()
    await admin.page.getByText('Failed attempt deleted.', { exact: true }).waitFor()
    assert.equal(await selectedTest.count(), 0)
    assert.equal(await db.assessment.count({ where: { id: { in: failedIds } } }), 50)
    // A search matching no rows must not silently narrow a class-wide cleanup.
    await library.getByLabel('Search student or version').fill('nothing-matches-this-filter')
    await library.getByText('No saved assessments match these filters.', { exact: true }).waitFor()
    admin.page.once('dialog', (dialog: any) => dialog.accept())
    await library.getByRole('button', { name: 'Delete failed attempts for this class', exact: true }).click()
    await library.getByText('Deleted 50 failed attempts.', { exact: true }).waitFor()
    assert.equal(await db.assessment.count({ where: { id: { in: failedIds } } }), 0)
    assert.ok(await db.assessment.findUnique({ where: { id: foreignFailure.id } }))
    assert.equal(await db.assessment.count({ where: { id: { in: [exam.id, queued.id, pendingFixture.id] } } }), 3)
    assert.equal(await db.ticket.count({ where: { id: { in: tickets.map(t => t.id) } } }), 3)
    assert.equal((await (await admin.api.delete('/api/assessments/failed', { data: cleanBody })).json()).deleted, 0)
    await db.assessment.delete({ where: { id: pendingFixture.id } })
    pass('confirmed failed-only cleanup protects roles, class boundaries, running/successful versions and student work')
    // Prove a canceled in-flight inference cannot publish stale results.
    await db.assessment.update({ where: { id: exam.id }, data: { createdAt: new Date(Date.now() - 120000) } })
    const cancel = await (await student.api.post('/api/assessments', { data: payload })).json()
    batch = 0
    await runAssessmentJob(db, async messages => { await student.api.patch(`/api/assessments/${cancel.id}`, { data: { action: 'cancel' } }); return fake(messages) })
    assert.equal((await db.assessment.findUniqueOrThrow({ where: { id: cancel.id } })).status, 'FAILED')
    await db.classWorkspace.update({ where: { id: classes[0].id }, data: { archivedAt: new Date() } })
    assert.equal((await student.api.post('/api/assessments', { data: payload })).status(), 409)
    assert.equal((await admin.api.delete('/api/assessments/failed', { data: cleanBody })).status(), 409)
    assert.equal((await student.api.get(`/api/assessments/${queued.id}`)).status(), 200)
    pass('cancel fences in-flight results; archived classes retain reads and reject generation')
    await db.classWorkspaceMember.deleteMany({ where: { classWorkspaceId: classes[0].id, userId: users[1].id } })
    assert.equal((await admin.api.get(`/api/assessments/${exam.id}`)).status(), 200)
    assert.equal((await admin.api.post('/api/assessments/canvas', { data: exportBody })).status(), 200)
    assert.equal((await student.api.get(`/api/assessments/${queued.id}`)).status(), 404)
    await db.classWorkspaceMember.create({ data: { classWorkspaceId: classes[0].id, userId: users[1].id } })
    pass('staff retain historical assessments after unenrollment without restoring student access')
    // Latest-class export chooses one accepted version per student, without letting
    // a newer unaccepted draft hide an older accepted exam.
    const savedExam = await db.assessment.findUniqueOrThrow({ where: { id: exam.id } })
    const cloneData = { studentId: users[1].id, classWorkspaceId: classes[0].id, createdById: users[0].id, mode: 'EXAM' as const, from: savedExam.from, to: savedExam.to, sources: savedExam.sources as any, questions: savedExam.questions as any, promptVersion: 'synthetic-batch' }
    const older = await db.assessment.create({ data: { ...cloneData, status: 'APPROVED', createdAt: new Date(Date.now() - 600000) } })
    const draft = await db.assessment.create({ data: { ...cloneData, status: 'READY' } })
    const otherExam = await db.assessment.create({ data: { ...cloneData, studentId: users[2].id, status: 'APPROVED' } })
    assert.equal((await admin.api.post('/api/assessments/canvas', { data: { ...exportBody, ids: [exam.id, draft.id] } })).status(), 409)
    const latest = await admin.api.post('/api/assessments/canvas', { data: { classId: classes[0].id, latestApproved: true, format: 'individual', points: 2 } })
    assert.equal(latest.status(), 200)
    const latestFiles = unzipSync(await latest.body()), index = JSON.parse(strFromU8(latestFiles['quiz-index.json']))
    assert.deepEqual(index.map((row: { version: string }) => row.version).sort(), [exam.id, otherExam.id].sort())
    assert.ok(index.every((row: { points: number }) => row.points === 50))
    assert.ok(!index.some((row: { version: string }) => row.version === older.id || row.version === draft.id))
    await db.assessment.deleteMany({ where: { id: { in: [older.id, draft.id, otherExam.id] } } })
    pass('class export chooses each student’s latest accepted exam and rejects mixed draft selections')
    assert.deepEqual(errors, [])
    if (process.env.ASSESSMENT_REAL_AI === '1') {
      await db.classWorkspace.update({ where: { id: classes[0].id }, data: { archivedAt: null } })
      await db.assessment.updateMany({ where: { studentId: users[1].id }, data: { createdAt: new Date(Date.now() - 120000) } })
      const real = await (await student.api.post('/api/assessments', { data: payload })).json()
      assert.ok(real.id)
      let realBatch = 0
      await runAssessmentJob(db, async (messages, options) => {
        const started = Date.now()
        const value = await chat(messages, options).catch(e => { console.log('Synthetic AI call failed: ' + String(e.message).slice(0, 160)); throw e })
        await import('node:fs/promises').then(fs => fs.writeFile(`${output}/synthetic-ai-batch-${realBatch++}.json`, value))
        console.log(`AI batch ${realBatch} returned in ${Math.round((Date.now() - started) / 1000)} seconds`)
        return value
      })
      const result = await db.assessment.findUniqueOrThrow({ where: { id: real.id } })
      assert.equal(result.status, 'READY', 'Configured model must return a validated 25-question test')
      await import('node:fs/promises').then(fs => fs.writeFile(output + '/synthetic-ai-questions.json', JSON.stringify(result.questions, null, 2)))
      pass('configured user-owned model generated a validated 25-question test from synthetic student work')
    }
    console.log(`PASS ${passCount} integration/browser groups; output ${output}`)
  } finally {
    await browser.close()
    await db.classWorkspace.deleteMany({ where: { id: { in: classes.map(c => c.id) } } })
    await db.user.deleteMany({ where: { id: { in: users.map(u => u.id) } } })
    await db.$disconnect()
  }
}
main().catch(e => { console.error(e instanceof Error ? e.message : 'Check failed'); process.exitCode = 1 })
