// Guarded synthetic fixtures only. Never run against the NAS.
import assert from 'node:assert/strict'
import { randomBytes, randomUUID } from 'node:crypto'
import { mkdir, readFile } from 'node:fs/promises'
import { PrismaClient } from '@prisma/client'
import bcrypt from 'bcryptjs'
import { parseCsv } from '../src/lib/cohort/csv'
const url = new URL(process.env.DATABASE_URL || 'file:///missing')
assert.equal(url.hostname, '127.0.0.1'); assert.equal(url.port, '55439'); assert.equal(url.pathname, '/sanctum_ga_check')
assert.equal(process.env.GA_BASE_URL, 'http://127.0.0.1:3459')
async function main() {
  const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright')
  const browser = await chromium.launch({ headless: true }), db = new PrismaClient({ log: [] })
  const suffix = randomUUID(), password = randomBytes(18).toString('hex'), hash = await bcrypt.hash(password, 10)
  const output = process.env.ROSTER_QA_OUTPUT || '/tmp/sanctum-roster-check'; await mkdir(output, { recursive: true })
  const userIds: string[] = [], classIds: string[] = [], emails: string[] = []
  const errors: string[] = []
  async function login(email: string, pass = password) {
    const context = await browser.newContext({ baseURL: process.env.GA_BASE_URL, viewport: { width: 1400, height: 1000 } })
    const csrf = await (await context.request.get('/api/auth/csrf')).json()
    await context.request.post('/api/auth/callback/credentials', { form: { csrfToken: csrf.csrfToken, email, password: pass, json: 'true' } })
    assert.ok((await (await context.request.get('/api/auth/session')).json()).user)
    return context
  }
  try {
    const admin = await db.user.create({ data: { email: `staff-${suffix}@example.invalid`, firstName: 'Roster', lastName: 'Instructor', role: 'ADMIN', passwordHash: hash } }); userIds.push(admin.id)
    const existing = await db.user.create({ data: { email: `Existing-${suffix}@example.invalid`, firstName: 'Existing', lastName: 'Student', role: 'TEAM_LEAD', passwordHash: hash } }); userIds.push(existing.id)
    const staff = await login(admin.email), student = await login(existing.email), anonymous = await browser.newContext({ baseURL: process.env.GA_BASE_URL })
    const response = await staff.request.post('/api/classes', { data: { name: 'Roster QA ' + suffix } }); assert.equal(response.status(), 201)
    const course = await response.json(); classIds.push(course.id)
    const originalTeam = await db.team.create({ data: { name: 'Existing group work', classWorkspaceId: course.id, members: { create: { userId: existing.id, role: 'MEMBER' } }, tickets: { create: { title: 'Keep this work', description: 'Unchanged evidence', createdById: admin.id, assigneeId: existing.id } } }, include: { members: true, tickets: true } })
    const endpoint = `/api/classes/${course.id}/students/import`
    const newEmail = `new-${suffix}@example.invalid`, secondEmail = `second-${suffix}@example.invalid`; emails.push(newEmail, secondEmail)
    const csv = `First name,Last name,Email\r\nNew,Student,${newEmail}\r\nSecond,Student,${secondEmail}\r\nExisting,Student,${existing.email.toLowerCase()}\r\n`
    const payload = { action: 'preview', csv }
    assert.equal((await anonymous.request.post(endpoint, { data: payload })).status(), 401)
    assert.equal((await student.request.post(endpoint, { data: payload })).status(), 403)
    assert.equal((await staff.request.post(endpoint, { data: { action: 'preview', csv: `First name,Last name,Email\nRoster,Instructor,${admin.email}` } })).status(), 400)
    assert.equal((await staff.request.post(endpoint, { data: { action: 'preview', csv: 'x'.repeat(200001) } })).status(), 413)
    assert.equal((await staff.request.post(endpoint, { data: { ...payload, csv: csv + `Duplicate,Student,${newEmail}\n` } })).status(), 400)
    const previewResponse = await staff.request.post(endpoint, { data: payload }); assert.equal(previewResponse.status(), 200); assert.equal(previewResponse.headers()['cache-control'], 'private, no-store')
    const preview = await previewResponse.json(); assert.deepEqual(preview.rows.map((r: any) => r.action), ['CREATE', 'CREATE', 'ENROLL'])
    assert.equal(await db.user.count({ where: { email: { in: emails } } }), 0)
    await db.user.update({ where: { id: existing.id }, data: { firstName: 'Changed' } })
    assert.equal((await staff.request.post(endpoint, { data: { ...payload, action: 'import', previewHash: preview.previewHash } })).status(), 409)
    assert.equal(await db.user.count({ where: { email: { in: emails } } }), 0)
    await db.user.update({ where: { id: existing.id }, data: { firstName: 'Existing' } })
    console.log('PASS authorization, CSV rejection, read-only preview and stale-preview protection')
    const page = await staff.newPage(); page.on('pageerror', () => errors.push('browser error'))
    await page.goto('/admin/classes')
    await page.locator('div.rounded-lg.border').filter({ has: page.getByText(course.name, { exact: true }) }).getByRole('button', { name: 'Import students', exact: true }).click()
    await page.getByLabel('Student roster CSV').setInputFiles({ name: 'roster.csv', mimeType: 'text/csv', buffer: Buffer.from(csv) })
    await page.getByRole('checkbox', { name: 'One Kanban per student' }).check()
    await page.getByRole('button', { name: 'Preview roster' }).click()
    await page.getByText('2 new accounts · 1 existing accounts to enroll · 0 already enrolled', { exact: true }).waitFor()
    await page.screenshot({ path: output + '/roster-preview-desktop.png', fullPage: true })
    await page.setViewportSize({ width: 390, height: 844 }); await page.screenshot({ path: output + '/roster-preview-mobile.png', fullPage: true }); await page.setViewportSize({ width: 1400, height: 1000 })
    await page.getByRole('button', { name: 'Import reviewed students' }).click()
    await page.getByText('Import complete: 2 accounts created, 3 students enrolled, 0 already enrolled.', { exact: true }).waitFor()
    assert.ok(await page.getByRole('button', { name: 'Close import' }).isDisabled())
    const downloadPromise = page.waitForEvent('download'); await page.getByRole('button', { name: 'Download new student logins' }).click()
    const download = await downloadPromise; const contents = parseCsv((await readFile(await download.path(), 'utf8')).replace(/^\uFEFF/, ''))
    assert.equal(contents.length, 3); assert.notEqual(contents[1][3], contents[2][3])
    for (const row of contents.slice(1)) { const u = await db.user.findUniqueOrThrow({ where: { email: row[2] } }); assert.equal(u.role, 'MEMBER'); assert.ok(await bcrypt.compare(row[3], u.passwordHash)); await (await login(row[2], row[3])).close() }
    const preserved = await db.user.findUniqueOrThrow({ where: { id: existing.id } }); assert.equal(preserved.passwordHash, hash); assert.equal(preserved.role, 'TEAM_LEAD'); assert.equal(preserved.firstName, 'Existing')
    assert.equal(await db.classWorkspaceMember.count({ where: { classWorkspaceId: course.id } }), 4)
    assert.equal((await staff.request.post(endpoint, { data: { ...payload, action: 'import', previewHash: preview.previewHash } })).status(), 409)
    const repeat = await (await staff.request.post(endpoint, { data: payload })).json()
    assert.ok(repeat.rows.every((r: any) => r.action === 'SKIP'))
    const repeated = await (await staff.request.post(endpoint, { data: { ...payload, action: 'import', previewHash: repeat.previewHash } })).json()
    assert.equal(repeated.created, 0); assert.equal(repeated.enrolled, 0); assert.deepEqual(repeated.credentials, [])
    assert.equal(await db.team.count({ where: { classWorkspaceId: course.id, individualOwnerId: { not: null } } }), 3)
    assert.deepEqual(await db.team.findUnique({ where: { id: originalTeam.id }, include: { members: true, tickets: true } }), originalTeam)
    const boardPreview = await (await staff.request.post(endpoint, { data: { ...payload, individualBoards: true } })).json()
    assert.ok(boardPreview.rows.every((r: any) => r.boardAction === 'KEEP'))
    assert.equal((await staff.request.post(endpoint, { data: { ...payload, action: 'import', individualBoards: false, previewHash: boardPreview.previewHash } })).status(), 409)
    const newStudent = await db.user.findUniqueOrThrow({ where: { email: newEmail } })
    const ownBoard = await db.team.findUniqueOrThrow({ where: { classWorkspaceId_individualOwnerId: { classWorkspaceId: course.id, individualOwnerId: newStudent.id } }, include: { members: true } })
    assert.equal(ownBoard.members.length, 1); assert.equal(ownBoard.members[0].role, 'LEAD')
    assert.equal(newStudent.role, 'MEMBER')
    const owner = await login(newEmail, contents.find(r => r[2] === newEmail)![3])
    const ticketResponse = await owner.request.post('/api/tickets', { data: { teamId: ownBoard.id, title: 'Individual investigation', description: 'Student evidence', status: 'BACKLOG' } })
    assert.equal(ticketResponse.status(), 200); const ticket = await ticketResponse.json(); assert.equal(ticket.assignee.id, newStudent.id)
    assert.equal((await student.request.post('/api/tickets', { data: { teamId: ownBoard.id, title: 'Not my board' } })).status(), 403)
    assert.equal((await owner.request.patch(`/api/tickets/${ticket.id}`, { data: { status: 'DOING' } })).status(), 200)
    assert.equal((await student.request.patch(`/api/tickets/${ticket.id}`, { data: { description: 'Not my work' } })).status(), 403)
    assert.equal((await owner.request.post(`/api/teams/${ownBoard.id}/members`, { data: { userId: existing.id } })).status(), 409)
    assert.equal((await staff.request.delete(`/api/teams/${ownBoard.id}/members?userId=${newStudent.id}`)).status(), 409)
    assert.equal((await owner.request.get(`/api/teams/${ownBoard.id}/export?from=2026-10-01&to=2026-10-31&view=gantt&paper=tabloid`)).status(), 200)
    assert.equal((await staff.request.patch(`/api/teams/${ownBoard.id}`, { data: { name: 'Renamed personal board' } })).status(), 200)
    const afterRename = await (await staff.request.post(endpoint, { data: { ...payload, individualBoards: true } })).json()
    assert.ok(afterRename.rows.every((r: any) => r.boardAction === 'KEEP'))
    const ownerPage = await owner.newPage()
    ownerPage.on('pageerror', () => errors.push('student browser error'))
    await ownerPage.goto(`/?classId=${course.id}`)
    await ownerPage.getByRole('button', { name: 'My Teams', exact: true }).click()
    await ownerPage.getByText('Individual board', { exact: true }).waitFor()
    await ownerPage.getByRole('button', { name: 'Add Ticket', exact: true }).click()
    const dialog = ownerPage.getByRole('dialog')
    assert.equal(await dialog.getByRole('combobox').filter({ hasText: 'New Student' }).count(), 1)
    await dialog.getByPlaceholder('Enter ticket title').fill('Browser individual task')
    const browserTicketResponse = ownerPage.waitForResponse((r: any) => r.url().endsWith('/api/tickets') && r.request().method() === 'POST')
    await dialog.getByRole('button', { name: 'Create Ticket', exact: true }).click()
    const browserTicket = await (await browserTicketResponse).json(); assert.equal(browserTicket.assignee.id, newStudent.id)
    await dialog.waitFor({ state: 'hidden' })
    await ownerPage.screenshot({ path: output + '/individual-student-board.png', fullPage: true })
    await owner.close()
    console.log('PASS individual import, account-role preservation, stable ownership, ticket attribution, board permissions and exports')
    console.log('PASS browser import, unique working logins, enrollment, preserved accounts and safe retries')
    const raceEmail = `race-${suffix}@example.invalid`; emails.push(raceEmail)
    const raceCsv = `firstName,lastName,email\nRace,Student,${raceEmail}`
    const race = await (await staff.request.post(endpoint, { data: { action: 'preview', csv: raceCsv } })).json()
    const raced = await Promise.all([1, 2].map(() => staff.request.post(endpoint, { data: { action: 'import', csv: raceCsv, previewHash: race.previewHash } })))
    assert.deepEqual(raced.map(r => r.status()).sort(), [200, 409]); assert.equal(await db.user.count({ where: { email: raceEmail } }), 1)
    await db.classWorkspace.update({ where: { id: course.id }, data: { archivedAt: new Date() } })
    assert.equal((await staff.request.post(endpoint, { data: payload })).status(), 409)
    assert.equal((await staff.request.post(endpoint, { data: { action: 'import', csv, previewHash: repeat.previewHash } })).status(), 409)
    await page.getByRole('button', { name: 'Close import' }).click()
    await page.getByRole('button', { name: 'New class', exact: true }).click()
    const newClassName = 'New roster class ' + suffix
    await page.getByPlaceholder('IST 4910 — Fall 2027').fill(newClassName)
    const createdResponse = page.waitForResponse((r: any) => r.url().endsWith('/api/classes') && r.request().method() === 'POST')
    await page.getByRole('button', { name: 'Create class', exact: true }).click()
    const createdClass = await (await createdResponse).json(); classIds.push(createdClass.id)
    await page.getByRole('heading', { name: 'Import students into ' + newClassName, exact: true }).waitFor()
    const canvasCsv = `Student,ID,SIS Login ID,Email,Section,Private grade\nPoints Possible,,,,,100\n"Student, New",11,new01,${newEmail},A,PRIVATE_GRADE_SENTINEL\n"Student, Second",12,second02,${secondEmail},A,PRIVATE_GRADE_SENTINEL`
    await page.getByLabel('Student roster CSV').setInputFiles({ name: 'canvas-gradebook.csv', mimeType: 'text/csv', buffer: Buffer.from(canvasCsv) })
    await page.getByRole('heading', { name: 'Canvas column mapping' }).waitFor()
    await page.getByRole('checkbox', { name: 'One Kanban per student' }).check()
    assert.equal(await page.getByLabel('Email column', { exact: true }).inputValue(), '3')
    const previewRequest = page.waitForRequest((r: any) => r.url().includes('/students/import') && r.method() === 'POST')
    await page.getByRole('button', { name: 'Preview roster' }).click()
    const sent = (await previewRequest).postDataJSON()
    assert.ok(!sent.csv.includes('PRIVATE_GRADE_SENTINEL')); assert.ok(!sent.csv.includes('SIS Login ID')); assert.ok(!sent.csv.includes('new01'))
    await page.getByText('0 new accounts · 2 existing accounts to enroll · 0 already enrolled', { exact: true }).waitFor()
    await page.getByLabel('Name format', { exact: true }).selectOption('first-last')
    assert.equal(await page.getByRole('button', { name: 'Import reviewed students' }).count(), 0)
    await page.getByLabel('Name format', { exact: true }).selectOption('last-first')
    await page.getByRole('button', { name: 'Preview roster' }).click()
    await page.getByRole('button', { name: 'Import reviewed students' }).waitFor()
    await page.screenshot({ path: output + '/canvas-roster-desktop.png', fullPage: true })
    await page.setViewportSize({ width: 390, height: 844 }); await page.screenshot({ path: output + '/canvas-roster-mobile.png', fullPage: true }); await page.setViewportSize({ width: 1400, height: 1000 })
    await page.getByRole('button', { name: 'Import reviewed students' }).click()
    await page.getByText('Import complete: 0 accounts created, 2 students enrolled, 0 already enrolled.', { exact: true }).waitFor()
    assert.equal(await db.classWorkspaceMember.count({ where: { classWorkspaceId: createdClass.id } }), 3)
    assert.equal(await db.team.count({ where: { classWorkspaceId: createdClass.id, individualOwnerId: { not: null } } }), 2)
    const boardEndpoint = `/api/classes/${course.id}/individual-boards`
    assert.equal((await anonymous.request.post(boardEndpoint, { data: { action: 'preview' } })).status(), 401)
    assert.equal((await student.request.post(boardEndpoint, { data: { action: 'preview' } })).status(), 403)
    assert.equal((await staff.request.post(boardEndpoint, { data: { action: 'preview' } })).status(), 409)
    await db.classWorkspace.update({ where: { id: course.id }, data: { archivedAt: null } })
    await page.getByRole('button', { name: 'Close import' }).click()
    await page.reload()
    await page.locator('div.rounded-lg.border').filter({ has: page.getByText(course.name, { exact: true }) }).getByRole('button', { name: 'One Kanban per student', exact: true }).click()
    await page.getByRole('button', { name: 'Preview individual boards' }).click()
    await page.getByText('1 boards to create · 3 existing individual boards to keep', { exact: true }).waitFor()
    await page.screenshot({ path: output + '/individual-boards-desktop.png', fullPage: true })
    await page.setViewportSize({ width: 390, height: 844 }); await page.screenshot({ path: output + '/individual-boards-mobile.png', fullPage: true }); await page.setViewportSize({ width: 1400, height: 1000 })
    await page.getByRole('button', { name: 'Create reviewed boards' }).click()
    await page.getByText('1 individual boards created; 3 existing boards kept.', { exact: true }).waitFor()
    const plan = await (await staff.request.post(boardEndpoint, { data: { action: 'preview' } })).json()
    assert.equal(plan.rows.length, 4); assert.ok(plan.rows.every((r: any) => r.action === 'KEEP'))
    const kept = await (await staff.request.post(boardEndpoint, { data: { action: 'create', previewHash: plan.previewHash } })).json()
    assert.deepEqual(kept, { created: 0, kept: 4 })
    // A roster change invalidates the class-wide preview, and simultaneous requests
    // create at most one board. Same-name students remain separate identities.
    const late = await db.user.create({ data: { email: `late-${suffix}@example.invalid`, firstName: 'New', lastName: 'Student', role: 'MEMBER', passwordHash: hash } }); userIds.push(late.id)
    await db.classWorkspaceMember.create({ data: { classWorkspaceId: course.id, userId: late.id } })
    assert.equal((await staff.request.post(boardEndpoint, { data: { action: 'create', previewHash: plan.previewHash } })).status(), 409)
    const changedPlan = await (await staff.request.post(boardEndpoint, { data: { action: 'preview' } })).json()
    const createdBoards = await Promise.all([1, 2].map(() => staff.request.post(boardEndpoint, { data: { action: 'create', previewHash: changedPlan.previewHash } })))
    assert.deepEqual(createdBoards.map(r => r.status()).sort(), [200, 409])
    assert.equal(await db.team.count({ where: { classWorkspaceId: course.id, individualOwnerId: late.id } }), 1)
    assert.equal(await db.team.count({ where: { classWorkspaceId: course.id, individualOwnerId: admin.id } }), 0)
    assert.deepEqual(await db.team.findUnique({ where: { id: originalTeam.id }, include: { members: true, tickets: true } }), originalTeam)
    const copiedResponse = await staff.request.post('/api/classes', { data: { name: 'Copy group only ' + suffix, copyTeamStructureFromId: course.id } }); assert.equal(copiedResponse.status(), 201)
    const copiedClass = await copiedResponse.json(); classIds.push(copiedClass.id); assert.equal(copiedClass._count.teams, 1)
    const deliverables = await staff.request.post(`/api/classes/${course.id}/deliverables`, { data: { deliverables: [{ title: 'Personal required assignment', description: 'Required research', kind: 'required' }] } })
    assert.equal(deliverables.status(), 200)
    const assigned = await db.ticket.findFirstOrThrow({ where: { teamId: ownBoard.id, title: 'Personal required assignment' } }); assert.equal(assigned.assigneeId, newStudent.id)
    console.log('PASS enrolled-student board UI, cross-class isolation, existing-work preservation, duplicate prevention, concurrency, stale previews, copy filtering and deliverable attribution')
    console.log('PASS Canvas mapping, parsed names, preview reset, enrollment and browser-side grade removal')
    assert.deepEqual(errors, [])
    console.log('PASS concurrent import rollback, archived-class protection and automatic import panel for a new class; synthetic fixtures cleaned up')
  } finally {
    await browser.close()
    await db.classWorkspace.deleteMany({ where: { id: { in: classIds } } })
    await db.user.deleteMany({ where: { OR: [{ id: { in: userIds } }, { email: { in: emails } }] } })
    await db.$disconnect()
  }
}
main().catch(e => { console.error(e.message); process.exitCode = 1 })
